import Head from "next/head";
import { useContext } from "react";
import AuthContext from "../contexts/AuthContext";
import Link from "next/link";
import Logout from "../components/Logout/Logout";

export default function Home() {
  const { user } = useContext(AuthContext);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>GERD Tracker</h1>
    </div>
  );
}
